CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('nutritionist', 'patient')),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  can_manage_nutrition_data BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_lower ON users (LOWER(email));

CREATE TABLE IF NOT EXISTS sessions (
  token_hash TEXT PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  nutritionist_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  birth_date DATE, sex TEXT CHECK (sex IN ('female', 'male', 'other') OR sex IS NULL),
  height_cm DOUBLE PRECISION CHECK (height_cm > 0), activity_level TEXT, objective TEXT,
  target_weight_kg DOUBLE PRECISION, food_preferences TEXT, food_restrictions TEXT,
  allergies TEXT, meal_routine TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS weight_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  weighed_at DATE NOT NULL, weight_kg DOUBLE PRECISION NOT NULL CHECK (weight_kg > 0),
  recorded_by BIGINT NOT NULL REFERENCES users(id), note TEXT, UNIQUE(patient_id, weighed_at)
);

CREATE TABLE IF NOT EXISTS nutrition_goals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  valid_from DATE NOT NULL, energy_kcal DOUBLE PRECISION, protein_g DOUBLE PRECISION,
  protein_gkg_min DOUBLE PRECISION, protein_gkg_max DOUBLE PRECISION,
  carbohydrate_g DOUBLE PRECISION, fat_g DOUBLE PRECISION, fiber_g DOUBLE PRECISION,
  water_ml DOUBLE PRECISION, created_by BIGINT NOT NULL REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(patient_id, valid_from)
);

CREATE TABLE IF NOT EXISTS nutrients (
  code TEXT PRIMARY KEY, name TEXT NOT NULL, tagname TEXT NOT NULL, unit TEXT NOT NULL,
  nutrient_group TEXT NOT NULL CHECK (nutrient_group IN ('energy', 'macro', 'mineral', 'vitamin', 'other')),
  sort_order INTEGER NOT NULL DEFAULT 999, UNIQUE(tagname, unit)
);

CREATE TABLE IF NOT EXISTS nutrient_goals (
  goal_id BIGINT NOT NULL REFERENCES nutrition_goals(id) ON DELETE CASCADE,
  nutrient_code TEXT NOT NULL REFERENCES nutrients(code), target_value DOUBLE PRECISION NOT NULL,
  PRIMARY KEY(goal_id, nutrient_code)
);

CREATE TABLE IF NOT EXISTS foods (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source TEXT NOT NULL CHECK (source = 'TACO'), source_code TEXT NOT NULL,
  description TEXT NOT NULL, normalized_name TEXT NOT NULL, scientific_name TEXT,
  category TEXT, brand TEXT, source_url TEXT,
  reference_amount DOUBLE PRECISION NOT NULL DEFAULT 100,
  reference_unit TEXT NOT NULL DEFAULT 'g', active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(source, source_code)
);

CREATE TABLE IF NOT EXISTS food_nutrients (
  food_id BIGINT NOT NULL REFERENCES foods(id) ON DELETE CASCADE,
  nutrient_code TEXT NOT NULL REFERENCES nutrients(code), numeric_value DOUBLE PRECISION,
  raw_value TEXT, status TEXT NOT NULL CHECK (status IN ('numeric', 'trace', 'missing')),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(food_id, nutrient_code),
  CHECK ((status = 'numeric' AND numeric_value IS NOT NULL) OR (status IN ('trace', 'missing') AND numeric_value IS NULL))
);

CREATE TABLE IF NOT EXISTS daily_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  log_date DATE NOT NULL, hunger INTEGER CHECK (hunger BETWEEN 1 AND 5 OR hunger IS NULL),
  satiety INTEGER CHECK (satiety BETWEEN 1 AND 5 OR satiety IS NULL),
  energy INTEGER CHECK (energy BETWEEN 1 AND 5 OR energy IS NULL),
  training TEXT, note TEXT, water_ml DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (water_ml >= 0),
  UNIQUE(patient_id, log_date)
);

CREATE TABLE IF NOT EXISTS meals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  daily_log_id BIGINT NOT NULL REFERENCES daily_logs(id) ON DELETE CASCADE,
  meal_type TEXT NOT NULL CHECK (meal_type IN ('breakfast', 'morning_snack', 'lunch', 'afternoon_snack', 'dinner', 'supper', 'other')),
  label TEXT, eaten_at TIMESTAMP, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS meal_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meal_id BIGINT NOT NULL REFERENCES meals(id) ON DELETE CASCADE,
  food_id BIGINT NOT NULL REFERENCES foods(id) ON DELETE RESTRICT,
  amount DOUBLE PRECISION NOT NULL CHECK (amount > 0), unit TEXT NOT NULL CHECK (unit IN ('g', 'ml')),
  grams_equivalent DOUBLE PRECISION NOT NULL CHECK (grams_equivalent > 0),
  consumed_at TIMESTAMP, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS favorites (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  food_id BIGINT NOT NULL REFERENCES foods(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id, food_id)
);

CREATE TABLE IF NOT EXISTS patient_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  author_user_id BIGINT NOT NULL REFERENCES users(id),
  visibility TEXT NOT NULL CHECK (visibility IN ('private', 'patient')),
  content TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS nutrition_import_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source TEXT NOT NULL CHECK (source = 'TACO'), source_file TEXT NOT NULL, source_size BIGINT NOT NULL,
  foods_processed INTEGER NOT NULL, foods_created INTEGER NOT NULL, foods_updated INTEGER NOT NULL,
  nutrients_created INTEGER NOT NULL, values_created INTEGER NOT NULL, values_updated INTEGER NOT NULL,
  missing_values INTEGER NOT NULL, trace_values INTEGER NOT NULL, zero_values INTEGER NOT NULL,
  errors INTEGER NOT NULL, imported_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_sessions_user_expiry ON sessions(user_id, expires_at);
CREATE INDEX IF NOT EXISTS idx_patients_nutritionist ON patients(nutritionist_user_id);
CREATE INDEX IF NOT EXISTS idx_weights_patient_date ON weight_history(patient_id, weighed_at DESC);
CREATE INDEX IF NOT EXISTS idx_foods_active_source ON foods(active, source);
CREATE INDEX IF NOT EXISTS idx_foods_normalized_trgm ON foods USING GIN(normalized_name gin_trgm_ops) WHERE active;
CREATE INDEX IF NOT EXISTS idx_food_nutrients_code_food ON food_nutrients(nutrient_code, food_id);
CREATE INDEX IF NOT EXISTS idx_daily_logs_patient_date ON daily_logs(patient_id, log_date DESC);
CREATE INDEX IF NOT EXISTS idx_meals_log ON meals(daily_log_id);
CREATE INDEX IF NOT EXISTS idx_meal_entries_meal ON meal_entries(meal_id);
CREATE INDEX IF NOT EXISTS idx_meal_entries_food ON meal_entries(food_id);
CREATE INDEX IF NOT EXISTS idx_meal_entries_consumed_at ON meal_entries(consumed_at);
CREATE INDEX IF NOT EXISTS idx_notes_patient_visibility ON patient_notes(patient_id, visibility, created_at DESC);
