CREATE TABLE activity_catalog (
 code TEXT NOT NULL, version TEXT NOT NULL, name TEXT NOT NULL, category TEXT NOT NULL,
 description TEXT NOT NULL, aliases TEXT[] NOT NULL, met DOUBLE PRECISION NOT NULL CHECK(met > 0),
 source TEXT NOT NULL, notes TEXT NOT NULL, resistance BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY(code, version)
);
CREATE TABLE activity_sessions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
 recorded_by BIGINT NOT NULL REFERENCES users(id),
 activity_date DATE NOT NULL, local_time TIME NOT NULL, timezone TEXT NOT NULL DEFAULT 'America/Sao_Paulo',
 duration_minutes DOUBLE PRECISION NOT NULL CHECK(duration_minutes > 0 AND duration_minutes <= 1440),
 intensity TEXT NOT NULL, outside_base BOOLEAN NOT NULL DEFAULT FALSE,
 snapshot JSONB NOT NULL, details JSONB NOT NULL DEFAULT '[]', note TEXT NOT NULL DEFAULT '',
 revision INTEGER NOT NULL DEFAULT 1,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_activity_patient_date ON activity_sessions(patient_id, activity_date, local_time);
CREATE TABLE activity_revisions (
 session_id BIGINT NOT NULL REFERENCES activity_sessions(id) ON DELETE CASCADE,
 revision INTEGER NOT NULL, previous_record JSONB NOT NULL, changed_by BIGINT NOT NULL REFERENCES users(id),
 changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(session_id, revision)
);
CREATE TABLE activity_favorites (
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 code TEXT NOT NULL, version TEXT NOT NULL, PRIMARY KEY(user_id, code, version),
 FOREIGN KEY(code,version) REFERENCES activity_catalog(code,version)
);
CREATE TABLE energy_settings (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
 valid_from DATE NOT NULL, mode TEXT NOT NULL CHECK(mode IN ('habitual_includes_exercise','base_plus_net')),
 factor DOUBLE PRECISION NOT NULL CHECK(factor BETWEEN 1 AND 2.5),
 clinical_review BOOLEAN NOT NULL DEFAULT FALSE, note TEXT NOT NULL,
 created_by BIGINT NOT NULL REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_energy_settings_date ON energy_settings(patient_id,valid_from DESC,id DESC);
CREATE TABLE energy_day_snapshots (
 patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE, day DATE NOT NULL,
 snapshot JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(patient_id,day)
);
CREATE TABLE energy_food_status (
 patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE, day DATE NOT NULL,
 complete BOOLEAN NOT NULL DEFAULT FALSE, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(patient_id,day)
);
