CREATE TABLE energy_base_revisions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
 day DATE NOT NULL, previous_snapshot JSONB,
 reason TEXT NOT NULL, changed_by BIGINT NOT NULL REFERENCES users(id),
 changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_energy_base_revisions_patient_day ON energy_base_revisions(patient_id,day);
