CREATE TABLE food_measures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  food_id BIGINT NOT NULL REFERENCES foods(id) ON DELETE CASCADE,
  key TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('mass','volume','count','household')),
  name TEXT NOT NULL CHECK (length(trim(name)) > 0),
  plural TEXT NOT NULL CHECK (length(trim(plural)) > 0),
  quantity NUMERIC NOT NULL CHECK (quantity > 0 AND quantity < 'Infinity'::numeric),
  grams NUMERIC NOT NULL CHECK (grams > 0 AND grams < 'Infinity'::numeric),
  source TEXT NOT NULL CHECK (length(trim(source)) > 0),
  reference TEXT NOT NULL CHECK (length(trim(reference)) > 0),
  is_default BOOLEAN NOT NULL DEFAULT false,
  UNIQUE(food_id, key)
);
CREATE UNIQUE INDEX food_measures_default ON food_measures(food_id) WHERE is_default;
ALTER TABLE meal_entries ADD COLUMN measure_snapshot JSONB;
ALTER TABLE meal_entries DROP CONSTRAINT meal_entries_unit_check;
ALTER TABLE meal_entries ADD CONSTRAINT meal_entries_unit_check CHECK (length(trim(unit)) > 0);
