CREATE TABLE meal_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  created_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  source_plan_id BIGINT REFERENCES meal_plans(id) ON DELETE SET NULL,
  version INTEGER NOT NULL CHECK (version > 0),
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','archived')),
  title TEXT CHECK (title IS NULL OR length(trim(title)) BETWEEN 1 AND 120),
  notes TEXT CHECK (notes IS NULL OR length(notes) <= 5000),
  lock_version INTEGER NOT NULL DEFAULT 0 CHECK (lock_version >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  published_at TIMESTAMPTZ,
  archived_at TIMESTAMPTZ,
  UNIQUE(patient_id, version),
  CHECK (
    (status = 'draft' AND published_at IS NULL AND archived_at IS NULL) OR
    (status = 'active' AND published_at IS NOT NULL AND archived_at IS NULL) OR
    (status = 'archived' AND published_at IS NOT NULL AND archived_at IS NOT NULL)
  )
);

CREATE UNIQUE INDEX meal_plans_one_active_per_patient
  ON meal_plans(patient_id) WHERE status = 'active';
CREATE INDEX idx_meal_plans_patient_status_version
  ON meal_plans(patient_id, status, version DESC);
CREATE INDEX idx_meal_plans_created_by ON meal_plans(created_by);

CREATE TABLE meal_plan_meals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meal_plan_id BIGINT NOT NULL REFERENCES meal_plans(id) ON DELETE CASCADE,
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 100),
  position INTEGER NOT NULL CHECK (position >= 0),
  meal_time TIME,
  notes TEXT CHECK (notes IS NULL OR length(notes) <= 2000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(meal_plan_id, position) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX idx_meal_plan_meals_plan_position
  ON meal_plan_meals(meal_plan_id, position);

CREATE TABLE meal_plan_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meal_plan_meal_id BIGINT NOT NULL REFERENCES meal_plan_meals(id) ON DELETE CASCADE,
  food_id BIGINT NOT NULL REFERENCES foods(id) ON DELETE RESTRICT,
  position INTEGER NOT NULL CHECK (position >= 0),
  amount DOUBLE PRECISION NOT NULL CHECK (amount > 0),
  unit TEXT NOT NULL CHECK (length(trim(unit)) > 0),
  grams_equivalent DOUBLE PRECISION NOT NULL CHECK (grams_equivalent > 0 AND grams_equivalent <= 5000),
  measure_snapshot JSONB,
  nutrient_snapshot JSONB CHECK (nutrient_snapshot IS NULL OR jsonb_typeof(nutrient_snapshot) = 'object'),
  notes TEXT CHECK (notes IS NULL OR length(notes) <= 1000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(meal_plan_meal_id, position) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX idx_meal_plan_items_meal_position
  ON meal_plan_items(meal_plan_meal_id, position);
CREATE INDEX idx_meal_plan_items_food ON meal_plan_items(food_id);
