CREATE TABLE meal_plan_item_substitutions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meal_plan_item_id BIGINT NOT NULL REFERENCES meal_plan_items(id) ON DELETE CASCADE,
  food_id BIGINT NOT NULL REFERENCES foods(id) ON DELETE RESTRICT,
  position SMALLINT NOT NULL CHECK (position BETWEEN 0 AND 2),
  amount DOUBLE PRECISION NOT NULL CHECK (amount > 0),
  unit TEXT NOT NULL CHECK (length(trim(unit)) > 0),
  grams_equivalent DOUBLE PRECISION NOT NULL CHECK (grams_equivalent > 0 AND grams_equivalent <= 5000),
  measure_snapshot JSONB,
  nutrient_snapshot JSONB CHECK (nutrient_snapshot IS NULL OR jsonb_typeof(nutrient_snapshot) = 'object'),
  origin TEXT NOT NULL CHECK (origin IN ('suggestion','manual')),
  algorithm_version TEXT NOT NULL,
  equivalence_metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(equivalence_metadata) = 'object'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(meal_plan_item_id, food_id),
  UNIQUE(meal_plan_item_id, position) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX idx_meal_plan_item_substitutions_item_position
ON meal_plan_item_substitutions(meal_plan_item_id, position, id);

CREATE INDEX idx_meal_plan_item_substitutions_food
ON meal_plan_item_substitutions(food_id);
