-- A fresh database has no nutrient definitions until the TBCA import runs.
-- Migration 029 stores a source-backed USDA food, so the canonical definitions
-- it references must exist before that migration is applied.
INSERT INTO nutrients(code,name,tagname,unit,nutrient_group,sort_order) VALUES
  ('vitamina_e_mg','Vitamina E','TOCPHA','mg','vitamin',1),
  ('acucar_adicao_g','Açúcar de adição','TBCA_ADDED_SUGAR','g','macro',2),
  ('carboidrato_disponivel_g','Carboidrato disponível','CHOAVLDF','g','macro',3),
  ('carboidrato_g','Carboidrato total','CHOCDF','g','macro',4),
  ('cinzas_g','Cinzas','ASH','g','other',5),
  ('cobre_mg','Cobre','CU','mg','mineral',6),
  ('colesterol_mg','Colesterol','CHOLE','mg','other',7),
  ('calcio_mg','Cálcio','CA','mg','mineral',8),
  ('energia_kcal','Energia','ENERC','kcal','energy',9),
  ('energia_kj','Energia','ENERC','kJ','energy',10),
  ('folato_equivalente_mcg','Equivalente de folato','FOLDFE','mcg','vitamin',11),
  ('ferro_mg','Ferro','FE','mg','mineral',12),
  ('fibra_g','Fibra alimentar','FIBTG','g','macro',13),
  ('fosforo_mg','Fósforo','P','mg','mineral',14),
  ('gordura_adicao_g','Gordura de adição','TBCA_ADDED_FAT','g','macro',15),
  ('lipideos_g','Lipídios','FAT','g','macro',16),
  ('magnesio_mg','Magnésio','MG','mg','mineral',17),
  ('manganes_mg','Manganês','MN','mg','mineral',18),
  ('niacina_mg','Niacina','NIA','mg','vitamin',19),
  ('potassio_mg','Potássio','K','mg','mineral',20),
  ('proteina_g','Proteína','PROCNT','g','macro',21),
  ('proteina_animal_g','Proteína animal','TBCA_ANIMAL_PROTEIN','g','macro',22),
  ('proteina_vegetal_g','Proteína vegetal','TBCA_PLANT_PROTEIN','g','macro',23),
  ('riboflavina_mg','Riboflavina','RIBF','mg','vitamin',24),
  ('sal_adicao_g','Sal de adição','TBCA_ADDED_SALT','g','other',25),
  ('selenio_mcg','Selênio','SE','mcg','mineral',26),
  ('sodio_mg','Sódio','NA','mg','mineral',27),
  ('tiamina_mg','Tiamina','THIA','mg','vitamin',28),
  ('umidade_g','Umidade','WATER','g','other',29),
  ('rae_ug','Vitamina A (RAE)','VITA RAE','mcg','vitamin',30),
  ('re_ug','Vitamina A (RE)','VITA','mcg','vitamin',31),
  ('vitamina_b12_mcg','Vitamina B12','VITB12','mcg','vitamin',32),
  ('piridoxina_mg','Vitamina B6','VITB6A','mg','vitamin',33),
  ('vitamina_c_mg','Vitamina C','VITC','mg','vitamin',34),
  ('vitamina_d_mcg','Vitamina D','VITD','mcg','vitamin',35),
  ('zinco_mg','Zinco','ZN','mg','mineral',36),
  ('monoinsaturados_g','Ácidos graxos monoinsaturados','FAMS','g','macro',37),
  ('poliinsaturados_g','Ácidos graxos poliinsaturados','FAPU','g','macro',38),
  ('saturados_g','Ácidos graxos saturados','FASAT','g','macro',39),
  ('trans_g','Ácidos graxos trans','FATRN','g','macro',40),
  ('alcool_g','Álcool','ALC','g','other',41)
ON CONFLICT(code) DO UPDATE SET
  name=excluded.name,
  tagname=excluded.tagname,
  unit=excluded.unit,
  nutrient_group=excluded.nutrient_group,
  sort_order=excluded.sort_order;
